FROM nginx:alpine

WORKDIR /opt

COPY auth.conf /etc/nginx/conf.d/auth.conf
COPY index.html /www/data/
COPY run.sh ./

# make sure root login is disabled
RUN sed -i -e 's/^root::/root:!:/' /etc/shadow

RUN rm /etc/nginx/conf.d/default.conf || :

CMD ["./run.sh"]
